CREATE DATABASE IF NOT EXISTS `bap_detective`;

USE `bap_detective`;

DROP TABLE IF EXISTS `people`;

CREATE TABLE `people` (
                          `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
                          `firstname` varchar(255) DEFAULT NULL,
                          `lastname` varchar(255) DEFAULT NULL,
                          `birthdate` varchar(255) DEFAULT NULL,
                          `city` varchar(255) DEFAULT NULL,
                          `description` text,
                          `company` varchar(255) DEFAULT NULL,
                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `people` (`id`, `firstname`, `lastname`, `birthdate`, `city`, `description`, `company`)
VALUES
(1,'Quemby','Travis','1951-09-24','Saint-Martin','diam luctus lobortis.','Gravida Mauris Ut Industries'),
(2,'Raymond','Harrington','1987-11-20','Sunset Point','Cum sociis natoque penatibus et magnis','Metus Urna Convallis PC'),
(3,'Shea','Albert','1967-07-01','Dave','sed dictum eleifend,','Sapien Foundation'),
(4,'Mara','Mooney','1949-05-18','Livo','placerat, augue. Sed molestie.','Tortor PC'),
(5,'Pandora','Grant','1980-06-26','Essex','tincidunt dui augue eu tellus. Phasellus elit','Ornare Egestas Ligula LLC'),
(6,'Ginger','Hodge','1988-06-11','Keiem','eu nibh vulputate mauris sagittis placerat. Cras','Ipsum Donec Institute'),
(7,'Calvin','Neal','1937-12-14','Tierralta','mollis vitae, posuere at, velit. Cras lorem','Laoreet Posuere Enim Inc.'),
(8,'Cadman','Horn','1981-07-04','Gwalior','erat nonummy ultricies ornare, elit elit fermentum','Erat Foundation'),
(9,'Brynn','Nolan','1996-02-29','Gifhorn','cubilia Curae; Donec tincidunt.','Nec Imperdiet Nec Corporation'),
(10,'Hadassah','Jacobson','1987-12-28','Mundare','orci quis lectus. Nullam suscipit, est ac facilisis','Ut Molestie Institute'),
(11,'Summer','Hensley','2001-01-06','Granada','Nullam feugiat','Dolor Tempus Industries'),
(12,'Price','Terrell','1943-10-01','Secunderabad','nonummy','Ac Mattis Velit PC'),
(13,'Angelica','Hawkins','1993-03-02','Mglin','vulputate eu, odio. Phasellus','Pellentesque Ultricies Dignissim Inc.'),
(14,'Melodie','Francis','1996-02-02','Lo Espejo','est.','Nunc Risus Ltd'),
(15,'Sylvester','Anderson','1952-03-24','Kayseri','accumsan laoreet ipsum.','Nam Consequat Dolor Institute'),
(16,'Emerald','Bradford','1974-02-01','Wazirabad','velit.','Integer LLP'),
(17,'Paki','Grant','1983-06-10','Karapınar','lorem tristique aliquet. Phasellus fermentum','Cursus Et Magna Inc.'),
(18,'Aurelia','Donovan','1981-09-26','Leticia','Phasellus at','Phasellus Ornare Fusce Company'),
(19,'Rylee','Herring','1950-07-17','Rutten','fringilla. Donec feugiat metus sit amet','Maecenas Iaculis Aliquet Associates'),
(20,'Wendy','Randall','1981-07-10','Dokkum','eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula','In Consectetuer Ipsum Associates'),
(21,'Tamara','Simmons','1936-11-11','Springdale','consectetuer euismod est arcu ac orci. Ut','Mauris Magna Foundation'),
(22,'Phelan','Gillespie','1997-10-25','Cervinara','Curabitur vel lectus. Cum','Sit Amet Diam Limited'),
(23,'Alana','Bullock','1961-05-30','Candela','augue ac ipsum. Phasellus vitae mauris sit','Tellus Imperdiet Non PC'),
(24,'Nichole','Reyes','1974-01-06','Barasat','nulla. Cras eu tellus eu augue','Augue Scelerisque Mollis Foundation'),
(25,'Keith','Douglas','2003-05-23','Acapulco','magnis','Proin Mi Ltd'),
(26,'Nayda','Patterson','1951-04-29','Wolvertem','Sed diam lorem, auctor quis, tristique ac,','Cras Industries'),
(27,'Palmer','Harmon','1957-01-10','Haveli','nisi. Mauris','Mauris Inc.'),
(28,'Jana','Witt','1949-04-21','Fontanigorda','enim.','Praesent Ltd'),
(29,'Ashton','Neal','1987-06-13','Enterprise','porta elit, a feugiat tellus lorem eu','Mollis Industries'),
(30,'Shea','Watts','1939-01-14','Flin Flon','pretium neque. Morbi quis','Nullam Suscipit Est Ltd'),
(31,'Curran','Aguirre','1984-04-07','Portigliola','molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.','Diam Inc.'),
(32,'Kato','Blackburn','1977-10-05','Wadgassen','facilisis lorem tristique aliquet. Phasellus fermentum convallis','Maecenas Malesuada Fringilla Inc.'),
(33,'Kimberley','Ellis','1996-07-26','Redwater','iaculis nec, eleifend non, dapibus','At Velit Incorporated'),
(34,'Caesar','Olson','1988-04-13','Wismar','sit amet, consectetuer adipiscing elit. Aliquam auctor, velit','Maecenas Iaculis Aliquet Consulting'),
(35,'Carol','Mills','1981-09-04','Montecarotto','at fringilla purus mauris a','Vivamus Molestie Dapibus Corp.'),
(36,'Fleur','Shelton','1975-09-22','Moorsele','nulla. Cras eu','Est Mauris Associates'),
(37,'Adele','Mann','1970-07-12','Melle','Sed nunc est, mollis non, cursus non,','Sit Amet Corp.'),
(38,'Maya','Castro','2000-01-10','Colchane','lobortis quam a felis','Arcu LLP'),
(39,'Nissim','Battle','1941-03-19','Gatchina','iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.','Ipsum Cursus Associates'),
(40,'Eaton','Dudley','1994-01-18','Dublin','eros turpis non','A Odio Semper Inc.'),
(41,'Jolene','Warren','1986-08-08','Borisovka','nec ante blandit viverra. Donec tempus,','Pretium Neque Inc.'),
(42,'Thaddeus','Mcintosh','1968-07-17','Chicago','Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat','Iaculis Limited'),
(43,'Gil','Shields','1952-11-04','Izel','imperdiet, erat nonummy ultricies ornare, elit elit','Tincidunt Orci Quis Limited'),
(44,'Penelope','Osborn','1956-01-16','Montbéliard','faucibus id, libero. Donec consectetuer mauris','Et Industries'),
(45,'Gail','Delgado','1965-08-23','Merzig','leo, in lobortis tellus justo sit amet nulla.','A Feugiat Tellus Corporation'),
(46,'Nigel','Sears','1989-11-19','Kapiti','fermentum fermentum arcu. Vestibulum ante ipsum primis in','Non Magna Nam Foundation'),
(47,'Rashad','Dickerson','2001-10-04','Frasnes-lez-Gosselies','non nisi. Aenean eget metus.','Cursus Integer Institute'),
(48,'Zoe','Love','1992-06-30','Montpelier','nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.','Risus Company'),
(49,'Darius','Cole','1973-06-13','Rupelmonde','id sapien. Cras dolor dolor, tempus non, lacinia at,','Gravida Aliquam LLP'),
(50,'Hilel','Carver','1964-02-14','Lauregno/Laurein','vitae odio sagittis semper. Nam','Fringilla Donec Feugiat LLP'),
(51,'Shaeleigh','Whitley','1997-11-08','Culemborg','id ante dictum cursus. Nunc','Scelerisque Inc.'),
(52,'Ezra','Owen','1948-06-21','Marchihue','consectetuer euismod est arcu ac orci. Ut','Tellus Phasellus Incorporated'),
(53,'John','Rowe','2006-11-30','Iquique','ultrices. Duis volutpat nunc sit','Ipsum Dolor Company'),
(54,'Philip','Good','1953-05-04','Orta San Giulio','Cras vulputate velit','Imperdiet Ullamcorper Duis Foundation'),
(55,'Erica','Fulton','1939-10-03','Beervelde','nibh. Phasellus nulla. Integer vulputate, risus a ultricies','Vel Incorporated'),
(56,'Lewis','Wolf','1942-09-17','Moose Jaw','Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum','Ante Nunc Mauris Corp.'),
(57,'Martha','Vincent','1942-12-01','Grande Prairie','eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna.','Elit Nulla Industries'),
(58,'Connor','Rojas','1988-06-03','Wemmel','mollis. Duis sit amet diam eu dolor egestas rhoncus.','Pellentesque Eget Dictum Foundation'),
(59,'Seth','Hall','1967-11-10','Dordrecht','ipsum ac mi eleifend egestas.','Ligula Consulting'),
(60,'Shaine','Salazar','2001-03-30','Lavoir','magna. Sed eu eros. Nam consequat dolor','Velit Egestas Limited'),
(61,'Armand','Diaz','1978-11-25','Westkapelle','lorem ipsum sodales purus, in molestie tortor nibh sit','In Institute'),
(62,'Wilma','Fleming','1966-04-30','Gijzelbrechtegem','rutrum non, hendrerit','Justo LLC'),
(63,'Fitzgerald','Holmes','1960-01-11','El Quisco','a purus.','Eu Nulla Ltd'),
(64,'Julie','Reilly','2003-03-23','Breton','mauris ipsum porta','Pede Corporation'),
(65,'Madonna','Kemp','1945-09-01','Newport','Aliquam vulputate ullamcorper magna. Sed eu','Risus Odio Auctor LLC'),
(66,'Gretchen','Brewer','1999-11-29','Ruette','Nulla aliquet. Proin velit. Sed malesuada augue','Id Associates'),
(67,'Guy','Bass','1934-05-19','Massa e Cozzile','molestie sodales. Mauris blandit enim consequat purus. Maecenas','Vestibulum Industries'),
(68,'Carly','Rojas','1995-03-09','Logan City','fermentum risus, at fringilla purus mauris a nunc. In at','Quis Diam Pellentesque Company'),
(69,'Odysseus','Gillespie','1965-06-16','Lobnya','vitae, posuere at, velit. Cras lorem lorem, luctus','Phasellus Libero Associates'),
(70,'Madeson','Cortez','1978-05-08','Broxburn','vel, venenatis vel, faucibus id, libero. Donec','Maecenas Malesuada PC'),
(71,'Oprah','Shaffer','1979-08-28','MŽlin','tristique pellentesque, tellus sem mollis','Nunc Est Mollis Associates'),
(72,'Ulric','Cobb','1988-05-25','Carson City','magna.','Aliquet Phasellus Fermentum Foundation'),
(73,'Grant','Holt','1939-02-18','Medea','iaculis odio. Nam interdum enim','Vulputate Lacus LLC'),
(74,'Aaron','Sparks','1954-06-27','Wood Buffalo','magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna','Morbi Neque Tellus PC'),
(75,'Phillip','Spears','1978-06-14','Garbsen','ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et','Lacinia Vitae Foundation'),
(76,'Maryam','Christensen','1994-07-31','Golitsyno','nibh dolor, nonummy','Mi Lacinia Mattis LLP'),
(77,'McKenzie','Rios','1964-01-24','Baisy-Thy','pharetra, felis eget','Erat Vel Pede Consulting'),
(78,'Levi','Cox','2001-08-11','Panihati','nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla','Cubilia Curae; Limited'),
(79,'Noel','Cummings','2004-12-21','Sibret','vehicula. Pellentesque tincidunt tempus risus. Donec egestas.','Lectus Nullam LLC'),
(80,'Blake','Bradshaw','1995-10-15','Houston','augue ac ipsum. Phasellus vitae mauris sit amet lorem','Id Blandit Inc.'),
(81,'Kennedy','Cross','1985-05-31','Bathurst','mi eleifend egestas. Sed pharetra, felis eget','Ut Foundation'),
(82,'Ashely','Maldonado','1963-06-16','Brin-Navolok','Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.','Sapien Inc.'),
(83,'Dennis','Mejia','1971-11-29','Raurkela Civil Township','luctus et ultrices','Fusce Feugiat Lorem Ltd'),
(84,'Shaine','Merrill','1986-05-27','Meeuwen','sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices','Purus Sapien Industries'),
(85,'Jacob','Lang','1998-03-11','Cumberland','sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra','Sed Nec Associates'),
(86,'Allistair','Kirk','1973-02-12','Bad Kreuznach','a, arcu. Sed et libero. Proin','Ut Limited'),
(87,'Mariko','Gallagher','1944-03-10','Nelson','lorem, vehicula et, rutrum eu, ultrices sit amet,','Libero Dui Nec Consulting'),
(88,'Kermit','Lloyd','1934-05-30','Ophoven','arcu. Sed','Egestas Institute'),
(89,'Charlotte','Riley','1948-05-03','Melbourne','ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam','Ipsum Dolor Sit PC'),
(90,'Jane','Thornton','2000-08-01','Caen','amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo','Tortor Dictum Company'),
(91,'Cruz','Church','1989-03-01','Maryborough','dui lectus rutrum urna, nec luctus felis purus','Lobortis Class Aptent Company'),
(92,'Kyle','Phelps','1983-04-23','Pamplona','Quisque imperdiet, erat','Ac Tellus Associates'),
(93,'Kyla','Holman','2004-02-18','San Giovanni Lipioni','augue eu tellus. Phasellus elit pede,','Proin Limited'),
(94,'Hayley','Watkins','1976-04-26','San Carlos','augue ut lacus.','Ut PC'),
(95,'Zephania','Pratt','2006-03-20','Fishguard','malesuada malesuada. Integer id magna et ipsum cursus','Cras Consulting'),
(96,'Phelan','Lawrence','1941-12-24','Campinas','lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,','Fermentum Fermentum Institute'),
(97,'Adara','Clayton','1951-10-20','Springfield','quis, pede. Praesent eu dui. Cum sociis natoque penatibus et','Sed Malesuada Company'),
(98,'Justina','Malone','1961-01-22','Delicias','penatibus et magnis','Mollis Vitae Industries'),
(99,'Emerson','Pace','1978-06-21','Waver','felis,','Egestas Nunc Sed Institute'),
(100,'Aladdin','Payne','1975-02-15','Bilaspur','semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices','Tellus Limited');
